# .github/release.yml

changelog:
  categories:
    - title: ✨ Features
      labels:
        - enhancement
        - documentation
    - title: 🐛 Bugs
      labels:
        - bug
    - title: 👒 Dependencies
      labels:
        - dependencies
