on:
  schedule:
    - cron: "0 11 * * *"

jobs:
  scrap:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout
        uses: actions/checkout@v4
      - name: 📦 Install dependencies
        run: npm install
      - name: 📊 Scrap
        run: node ./scripts/scrapper.js
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TMDB_API_KEY: 4090bdb7b4e54aec7be3b4bcd54150b7
          TMDB_ACCESS_TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI0MDkwYmRiN2I0ZTU0YWVjN2JlM2I0YmNkNTQxNTBiNyIsIm5iZiI6MTczMjAzODU3NC4wNTkyOTQ1LCJzdWIiOiI2NzNjY2ViNTE5YWMzMmNlYjFiZDM3ZmMiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.Z-SWHYucmy40ZPJYUdobVJtkawTjtJNSoGqBxcligpQ
          DATABASE_URL: postgresql://postgres:gt2Gyj4ZuAFQycBt@db.yafeugsphejhrcwqmesx.supabase.co:5432/postgres
